version: "3.9"
services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - CPP_PORT=4000
      - CPP_HOST=cpp_server
      - JWT_SECRET=someSuperSecretStringHere
      - MONGO_URL=mongodb://mongo:27017/gmailish?replicaSet=rs0
    command: ["npm", "run", "dev"]
    restart: unless-stopped
    depends_on:
      cpp_server:
        condition: service_started
      mongo:
        condition: service_healthy

  cpp_server:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    command: ["./cpp_server", "4000", "1024", "3", "5"]
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"         # optional: expose to host
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d  # optional: seed scripts
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://localhost:27017", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

volumes:
  mongo_data:
